### ISSUE TITLE
[PIMCORE5] Installation issues

### ISSUE THREAD

**Issue by jkaufma** [pimcore/pimcore#1562]
# Bug Report
I experienced two issues during installation of Pimcore 5 (5.0.0-BETA1 Build: 61).  LAMP stack (Ubuntu 16.04.2 LTS / PHP 7.0).
Maybe the first one relates to #1454, but I'm not sure.

## 1) _Check Requirements_ does not work before installation.
Only an empty bowser window/tab opens and the following messages are logged in in `var/logs/php.log`:
```
[31-May-2017 17:51:52 Europe/Berlin] PHP Fatal error:  Allowed memory size of 1073741824 bytes exhausted (tried to allocate 409600 bytes) in /opt/pimcore-5/vendor/monolog/monolog/src/Monolog/Logger.php on line 323
[31-May-2017 17:51:52 Europe/Berlin] PHP Fatal error:  Uncaught Doctrine\DBAL\ConnectionException: There is no active transaction. in /opt/pimcore-5/vendor/doctrine/dbal/lib/Doctrine/DBAL/ConnectionException.php:42
Stack trace:
#0 /opt/pimcore-5/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(1285): Doctrine\DBAL\ConnectionException::noActiveTransaction()
#1 /opt/pimcore-5/pimcore/lib/Pimcore/Cache/Pool/Doctrine.php(238): Doctrine\DBAL\Connection->rollBack()
#2 /opt/pimcore-5/pimcore/lib/Pimcore/Cache/Pool/AbstractCacheItemPool.php(394): Pimcore\Cache\Pool\Doctrine->commit()
#3 /opt/pimcore-5/pimcore/lib/Pimcore/Cache/Core/CoreHandler.php(562): Pimcore\Cache\Pool\AbstractCacheItemPool->save(Object(Pimcore\Cache\Pool\CacheItem))
#4 /opt/pimcore-5/pimcore/lib/Pimcore/Cache/Core/CoreHandler.php(854): Pimcore\Cache\Core\CoreHandler->storeCacheItem(Object(Pimcore\Cache\Pool\CacheItem), 'failed', false)
#5 /opt/pimcore-5/pimcore/lib/Pimcore/Cache/Core/CoreHandler.php(903): Pimcore\Cache\Core\CoreHandler->writeSaveQueue()
#6 /opt/pimcore-5/pimcore/lib/Pimcore/Cach in /opt/pimcore-5/vendor/doctrine/dbal/lib/Doctrine/DBAL/ConnectionException.php on line 42
```

From the related message in `var/logs/prod.log` it seems that the wrong database credentials are used:
```
[2017-05-31 17:51:52] cache.WARNING: Failed to fetch key "system_route_redirect" {"key":"system_route_redirect","exception":"[object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO) at /opt/pimcore-5/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:103, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO) at /opt/pimcore-5/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:47, PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO) at /opt/pimcore-5/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43)"} []
```

After a successful installation I can perform a _System-Requirements Check_ without error.

## 2) File permissions are insufficient for installation.
When setting write permissions only to the directories `web/var`, `var` and `pimcore` according to https://www.pimcore.org/docs/5.0.0/Installation_and_Upgrade/System_Setup_and_Hosting/File_Permissions.html the installation fails with an error (s. Screenshot):
![pimcore-5-install-error](https://cloud.githubusercontent.com/assets/8115230/26676866/d402934c-46c9-11e7-93ab-836fb9cf535f.png)
After setting write permissions to the complete installation directory
```
/opt/pimcore-5$ sudo chown -R www-data:www-data .
```
the installation succeeded.

I hope this helps to improve the installation process.  Thank you for your work.

**Comment by brusch** [comment]
fixed by 1ea5b8615f129f981f1af283ce19709b90d3a7e1 (1) and 1bb6d3161ddaf3d1964c17fddb1e5dd2a6cb8a82 (2)

**Comment by jkaufma** [comment]
I have done a clean installation of version 5.0.0-BETA1, Build: 64 and just want to give you feedback:

Now _Check Requirements_ works before installation. :+1:  It seems that the error message I posted above has nothing to do with the problem, because the message appears even during a successful installation.

Regarding the 2nd issue, giving additional write access to `app/config` still isn't sufficient.  Now the installation stops with the following error:
![pimcore-5-install-error-new-p](https://user-images.githubusercontent.com/8115230/26940098-b8c25832-4c79-11e7-9f6e-7e39ea94eeb1.png)

I think the main reason is that the installer wants to move `install-profiles` to `install-profiles-installed` within the project directory.  Therefore I think the only solution is to give write permissions to the whole project directory.
