### ISSUE TITLE
[Bug]:  Forgot password doesn't work

### ISSUE THREAD

**Issue by shades3002** [pimcore/pimcore#17471]
### Pimcore version

11.1.0

### Steps to reproduce

Step 1. Click on Forgot your password
Step 2. Enter the user name you want to reset your password for
Step 3. Click on Submit

This generic error message appears: An error occured when resetting password: Please make sure you are entering a correct input.
Please retry again later or contact an administrator.

Email sending works correctly for the other features. This is the only one that did not work correctly. Here is the login/lostpassword url

![Screenshot 2024-08-08 at 9 59 31 AM](https://github.com/user-attachments/assets/7bc93855-b083-43e3-8883-1915291b3cf2)

### Actual Behavior

This generic error message appears: An error occured when resetting password: Please make sure you are entering a correct input.
Please retry again later or contact an administrator.

### Expected Behavior

Instead of returning the generic error, it should send an email but it doesn't, it can indicate if there is any extra configuration that could cause the problem.

**Comment by mattamon** [comment]
Hey @shades3002,

can you please check the logs for additional infos. This error message is very generic on purpose so we do not disclose the error details. 
In the logs you should find a line starting with `Lost password service:` which has some additional info to what went wrong.
Additionally, this concerns the login and should be moved to the admin-classic-ui-bundle instead.

**Comment by medovanx** [comment]
same on pimcore v10.6

**Comment by medovanx** [comment]
Same on pimcore v10.6.9
Logs
`[2024-09-18T08:23:25.018410+00:00] pimcore.ERROR: Error sending password recovery email: An exception occurred while executing 'SELECT * FROM email_blocklist WHERE address = ?' with params ["xxx"]:  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'bitnami_pimcore.email_blocklist' doesn't exist [] []`


Update:
fixed with applying doctrine migration scripts

**Comment by mattamon** [comment]
@medovanx Thanks for the update.
So now everything works fine after executing the migrations?

@shades3002 Does the issue still exist? Did you try to run the migrations? 

Otherwise I would close this issue as resolved.

**Comment by medovanx** [comment]
> @medovanx Thanks for the update.
> So now everything works fine after executing the migrations?
> 
> @shades3002 Does the issue still exist? Did you try to run the migrations? 
> 
> Otherwise I would close this issue as resolved. 

Yep worked after running the migration (I was on 10.x), I faced it again (after upgrading to 11.4)  but fixed it by setting main domain in pimcore settings from dashboard.

**Comment by mattamon** [comment]
@shades3002 I am closing the issue now. As described please have a look at the logs and check if the migrations were executed successfully and maybe also try setting your main domain like @medovanx said. 

You can open up another ticket anytime!
