### ISSUE TITLE
[Ecommerce][Bug] Price rule AND/OR conditions

### ISSUE THREAD

**Issue by NiklasBr** [pimcore/pimcore#4056]
# Bug Report

### Expected behavior

The price rule condition Product AND in conjunction with the Product Discount action should apply to all matches and only those matching.

The price rule Product OR in conjunction with the Product Discount action should apply to any matches.

([Gitter conversation](https://gitter.im/pimcore/pimcore?at=5c82754f3162ec7bc73c0e60))

### Actual behavior

The rule condition Product AND causes all products in cart to get a Product Discount, even those not matching the condition.

The rule condition Product OR causes only the first product in the cart to get the Product Discount, even if other products match the condition.

### Steps to reproduce

1. Create a rule (active, additive) 
2. With the conditions [product: 123] AND [product: 567]
3. And the action [product discount: 10%]
4. Add product 123, 567, and 985 to the cart

Result: All products gets the product discount.
Expected behaviour: The two products 123 and 567 should be discounted.

5. Create a rule (active, additive)
6. With the conditions [product: 123] OR [product: 567]
7. And the action [product discount: 10%]
8. Add product 123, 567, and 985 to the cart

Result: Only the first product of 123 or 567 gets discounted.
Expected behaviour: The two products 123 and 567 should be discounted.

This might be a bit of semantic wrangling, but the last expected behaviour is not an OR behaviour it's an XOR behaviour. I would expect the OR to mean "may match this one or may match that one, may match both to return true for those matching".

**Comment by AlternateIf** [comment]
I also experienced the second test case (OR Condition). It seems like the first item is always AND coupled. Until the bug is fixed, you can put a parenthese around your condition or you can move the first condition down then change the condition to OR and move it back up

![image](https://user-images.githubusercontent.com/14984260/54189915-12fe4800-44b3-11e9-9695-fa8fb47017c5.png)

**Comment by dvesh3** [comment]
fixed by #7904

**Comment by Daniel-Ateles** [comment]
This bug seems to have resurfaced in later versions, eg 10.4.1.

**Comment by dvesh3** [comment]
@Daniel-Ateles can you please try on latest version 10.5.2?

**Comment by Daniel-Ateles** [comment]
@dvesh3 now I'm on 10.5.2 and this problem still exists. Doesn't matter if I use paranthesis with AND/OR etc. All products in the cart get the discount, even products not in the rules.

**Comment by Daniel-Ateles** [comment]
@dvesh3 To me it looks like ProductQuantity->check ignores the product it's about to check and only iterates over all the cart products and check if any of the cart products is valid for any of the rules?

**Comment by Daniel-Ateles** [comment]
I found an opportunity to optimize ProductQuantity->check.
It is being called from PricingManager->applyCartRules where the product is set to null and only categories are set in the "environment"-object (probably to take care of rules operating on categories?). This should give us the opportunity to quit early in ProductQuantity->check if the product is set to null and skip it alltogether.

**Comment by dvesh3** [comment]
@Daniel-Ateles sorry not able to reproduce it on latest version. when using OR condition the product discount is applied on the products that are defined in the condition
![image](https://user-images.githubusercontent.com/5137917/184893541-89d378b1-6228-4cad-ab29-bba0ff253bdc.png)

what is your rule look like? If you are using Cart discount action then discount is applied on overall cart not to specific products.

**Comment by Daniel-Ateles** [comment]
> @Daniel-Ateles sorry not able to reproduce it on latest version. when using OR condition the product discount is applied on the products that are defined in the condition

Yes that works fine. Unfortunately products not in the conditions also gets the discount.

> what is your rule look like? If you are using Cart discount action then discount is applied on overall cart not to specific products.

It's a Product Discount, not a cart discount. When I add the following code it works as expected:

```
   public function check(EnvironmentInterface $environment): bool
    {
        .....
		// Quit and return false if the rule doesn't contain the product we're checking
		if (!$this->productExistsInArray($environment->getProduct(), $info['products'])) {
			return false;
		}
       .....
```

**Comment by dvesh3** [comment]
> Unfortunately products not in the conditions also gets the discount.

@Daniel-Ateles Not for me. please see the screenshot [above](https://github.com/pimcore/pimcore/issues/4056#issuecomment-1216654746), the last product was not in the condition and no discount was applied on it.

**Comment by Daniel-Ateles** [comment]
> the last product was not in the condition and no discount was applied on it.

Aha, sorry for not checking out your screenshot. You only have one Product Quantity rule?
We have two with one product discount.
![image](https://user-images.githubusercontent.com/58037739/185592120-b603d150-a54a-4309-b87c-a95ebf566696.png)

**Comment by Daniel-Ateles** [comment]
The reason both contains the same two products is the way the code applies the discounts.

**Comment by Daniel-Ateles** [comment]
In clear text the discount reads "Only apply the discount to the two products if the two products have a quantity >= 10"

**Comment by dvesh3** [comment]
@Daniel-Ateles I think you are looking at a custom implementation of the Pricing Rule as we don't have "Product Quantity" implemented in the core.
![image](https://user-images.githubusercontent.com/5137917/185595231-4d930b66-6752-46eb-a380-b8877ac5c8d6.png)

**Comment by Daniel-Ateles** [comment]
Ugh. How embarrassing. You are correct. I'm very sorry for wasting your time. I will investigate how I could make this mistake and learn from it so it doesn't happen again.
