### ISSUE TITLE
REST API Import problem with localized field in field collection in class

### ISSUE THREAD

**Issue by drahreg** [pimcore/pimcore#4767]
Hello,

first of all i have to say i don't have much to do with pimcore i just had to debug some code today and came across the following:

We have a class and in this one we used Field Collections with localized values

When we wanted to import via the REST API we got the following error:

```
{
    "success": false,
    "msg": "Call to a member function isEqual() on null"
}
```

I looked at the code locations and it is

https://github.com/pimcore/pimcore/blob/0e9fe183fb435b8882080424f425a7726e479b27/models/DataObject/Localizedfield.php#L519-L535

So $fieldDefinition is ```null``` in line 533

In our case the ```$fieldDefinition``` is set in line 519 and called with the object of type of our class (not the field collection)

So this function

https://github.com/pimcore/pimcore/blob/0e9fe183fb435b8882080424f425a7726e479b27/models/DataObject/ClassDefinition/Data/Localizedfields.php#L846-L861

is returning ```null``` and ```isEqual``` can not be called

I then looked at the method ```isEqual``` and it always returns false anyway

https://github.com/pimcore/pimcore/blob/0e9fe183fb435b8882080424f425a7726e479b27/models/DataObject/ClassDefinition/Data.php#L1382-L1385

and therefore took out the check in the if 

```
if ($markFieldAsDirty)
```

and now our import works.

Maybe someone who has more experience with Pimcore can take a look at this.

**Comment by brusch** [comment]
This is not for support, please use out forums or the Gitter chat. 
Thanks!

**Comment by kevingimbel** [comment]
@brusch your answer may be an automated or saved response but this is not a support question. There's a bug in Pimcore and this is a report for it. 

For what else is GitHub issues used if not to report bugs? If you don't want bug reports just close the issues section all together.

**Comment by dpfaffenbauer** [comment]
@brusch This is not a support request, this is a bug in Pimcore and even though the webservice is already deprecated, should still be fixed in FieldCollections.

**Comment by brusch** [comment]
PRs are welcome, maybe one of the down-voters? 😉

**Comment by TimPietrusky** [comment]
@drahreg could you please take a look at the commit that was referenced and see if that might fix our problem?

**Comment by TimPietrusky** [comment]
We updated to 6.4.2 and we still have the same problem. Is there anything we have to do with the attribute itself? Or what can I do in order to help resolve this issue?
