### ISSUE TITLE
Custom views do not update

### ISSUE THREAD

**Issue by John5** [pimcore/pimcore#512]
When editing objects in custom views, the publising state of an object does not update in the sidebar when (un)publishing an object. It should work the same as in the "objects" panel.

**Comment by weisswurstkanone** [comment]
fixed in build 3696

**Comment by weisswurstkanone** [comment]
sorry, there was a commit missing. fixed in build 3697

**Comment by woellundwoell** [comment]
It seems to be the same in 4.0.0 (build 3777). The object tree does not update after publish/unpublish/create/delete in custom views.

**Comment by weisswurstkanone** [comment]
We have completely refactored this topic after 3777. Please try the latest build.

**Comment by woellundwoell** [comment]
Thanks for your quickly response! We've now updated to build 3794, cleared all caches and even restarted the webserver - but the problem is still the same.

**Comment by brusch** [comment]
Are you using the new (modern) ui (extjs 6) or the legacy? 
The functionality described above is only available using the modern user interface.

**Comment by woellundwoell** [comment]
We are using the extjs 6 ui.
Maybe it is important to know that we are also using perspectives to generate the custom views...

**Comment by weisswurstkanone** [comment]
Unable to reproduce this using the setup as in the examples. See screencast. Could you please provide your customviews.php and perspectives.php files ?
[unpublish.zip](https://github.com/pimcore/pimcore/files/281294/unpublish.zip)

**Comment by woellundwoell** [comment]
Attached our screencast. In the next post we will provide the sourcees
[pimcore.mp4.zip](https://github.com/pimcore/pimcore/files/281339/pimcore.mp4.zip)

**Comment by woellundwoell** [comment]
We have no customviews.php. Our perspectives.php looks like this:
```

<?php
use Pimcore\Model\Object\Administrator;
use Pimcore\Model\Object\Service;
use Website\Helper\Perspective;

$pimcoreUser = \Pimcore\Tool\Admin::getCurrentUser();

$qadminList = Service::getObjectsReferencingUser($pimcoreUser->getId());
$qadmin = reset($qadminList);
$administrator = null;
if($qadmin instanceof Administrator) {
	$administrator = $qadmin;
}
return Perspective::getPerspectiveArrayByAdministrator($administrator);
```
and returns the following data (from ZendDebug::dump()) for the according user. The according user has configured in the pimcore user administration the "hrAdmin"-perspective:
```
array(1) {
  ["hrAdmin"] => array(3) {
    ["iconCls"] => string(24) "pimcore_icon_perspective"
    ["elementTree"] => array(1) {
      [0] => array(15) {
        ["treetype"] => string(6) "object"
        ["name"] => string(12) "Test germany"
        ["condition"] => NULL
        ["icon"] => string(29) "/static/img/icons/company.png"
        ["id"] => int(3)
        ["rootfolder"] => string(34) "/customer/test-group/01_companies/"
        ["showroot"] => bool(false)
        ["classes"] => string(0) ""
        ["position"] => string(4) "left"
        ["sort"] => string(2) "-1"
        ["expanded"] => bool(true)
        ["having"] => string(0) ""
        ["joins"] => array(0) {
        }
        ["where"] => string(0) ""
        ["type"] => string(10) "customview"
      }
    }
    ["dashboards"] => array(1) {
      ["predefined"] => array(1) {
        ["welcome"] => array(2) {
          ["positions"] => array(2) {
            [0] => array(3) {
              ["id"] => int(1)
              ["type"] => string(48) "pimcore.layout.portlets.missingTaskUserRelations"
              ["config"] => NULL
            }
            [1] => array(3) {
              ["id"] => int(2)
              ["type"] => string(40) "pimcore.layout.portlets.missingTrainings"
              ["config"] => NULL
            }
          }
          [0] => array(0) {
          }
        }
      }
    }
  }
}
```

**Comment by weisswurstkanone** [comment]
Unable to reproduce it with the same steps from your screencast. Will investigate your perspectives.php now ...

**Comment by weisswurstkanone** [comment]
Hmm, you provide the plain perspectives.php source code?

**Comment by weisswurstkanone** [comment]
Did you check for errors in the javascript console. Nothing apparently wrong with your configuration ...

**Comment by woellundwoell** [comment]
Yes, we did provide the plan soirce code. In the last line we call the getPerspectiveArrayByAdministrator() function. This returns the array shown above.

**Comment by weisswurstkanone** [comment]
OK, the reason is that (for custom views) you have to define the custom view settings in the custom view file rather than in the perspectives file. You then link them together via the ID value.
You can find an example in the perspectives.php.example and customviews.php.example file.
The reason behing this approach is that we want to define the customviews only once and then reuse  them in different perspectives. The perspectives.php file is then merely used to define which customviews you want to display and where the tree should be located.

**Comment by woellundwoell** [comment]
OK, we found out some more facts:
- When providing customviews only by cusomviews.php thinks works fine. ;)
- When providing customvies only by perspectives.php (in our case) the problem ist as decribed above
- The problem still exist if we provide custom view AND objects-section-pane 
- When hiding the objects-section-pane by perspectives.php and only show the pane for the custom view the button "show in tree" is not displayed
- A js error is not displayed in the console.

**Comment by weisswurstkanone** [comment]
#1) that's the standard behavior
#2) that's what I mentioned in my last post
#3) please again provide both samples
#4) that is intentional. currently we only expand the main tree. if it is hidden it doesn't make sense to even show the button
#5) good

**Comment by woellundwoell** [comment]
Thanks a lot for your post. I've seen it after my last. ;)
#4 -> You are really right. :)  We hoped that it is possible to show the node / object in the tree of the custom view.
We will try out 2 other solutions and will than post again.

**Comment by weisswurstkanone** [comment]
Problem with #4 is that it is quite hard to decide which one to expand if you have more of them.
The first one? All of them? Not really sure ...
Next thing is that you probably don't beforehand which tree even contains the object you are looking for.

**Comment by woellundwoell** [comment]
Yes, of corse! ;)

**Comment by weisswurstkanone** [comment]
I could imagine a split button offering the available trees. If you pick the wrong it is your fault :-)

**Comment by woellundwoell** [comment]
Thank you very much for your support! It helps us a lot to solve the problem in the following way:
We refference only one (and always the same) custom view id in the perspectives.php und return the array dynamically in the customviews.php (for the according logged in user).
Every thing works fine now.

**Comment by weisswurstkanone** [comment]
Nice to hear. Can we close this issue then (and maybe create "Improvement" tickets for the excellent inputs)?

**Comment by woellundwoell** [comment]
Yes, with pleasure.;)

**Comment by weisswurstkanone** [comment]
thx!
