### ISSUE TITLE
Symfony 4.4 Compatibility

### ISSUE THREAD

**Issue by BenjaminEden** [pimcore/pimcore#5302]
# Bug Report

Running "composer update" updates Symfony to 4.4.

The installation breaks with message:

> PHP Fatal error:  Declaration of Pimcore\Controller\Controller::setContainer(Psr\Container\ContainerInterface $container) must be compatible with Symfony\Bundle\FrameworkBundle\Controller\AbstractController::setContainer(Psr\Container\ContainerInterface $container)

I think the interface has changed.

Updated from Pimcore 4.3.1. to 4.3.2.

**Comment by zeor59** [comment]
Hello

Same problem when trying to upgrade Pimcore V 6.3.2 > V 6.3.3 with composer update command : 

```
[RuntimeException]
  An error occurred when executing the "'cache:clear --no-warmup'" command:


  Fatal error: Declaration of Pimcore\Controller\Controller::setContainer(Psr\Container\ContainerInterface $container) must be compatible with Symfony\Bundle\FrameworkBundle\Controller\AbstractController::setContainer(Psr\Container\Co
  ntainerInterface $container): ?Psr\Container\ContainerInterface in /var/www/html/vendor/pimcore/pimcore/lib/Controller/Controller.php on line 20
```

**Comment by BenjaminEden** [comment]
It's not a problem with the update of Pimcore. I've done that yesterday or a day before without a problem. Symfony 4.4 wasn't released by then. ;)

**Comment by fuzolan** [comment]
Yesterday the update on a test-instance went fine...today i have also this message...

**Comment by fuzolan** [comment]
the lockfile from yesterday works fine ....

  - Downgrading symfony/symfony (v4.4.0 => v4.3.8): Loading from cache
  - Installing fig/link-util (1.0.0): Loading from cache
  - Downgrading scheb/two-factor-bundle (v3.25.0 => v3.24.0): Loading from cache

**Comment by BenjaminEden** [comment]
Thanks Bernhard for the quick fix!

**Comment by brusch** [comment]
Caused by the release of Symfony 4.4. Issue is fixed already (see above). 
We'll tag a release soon (after doing some further testing). 

In the meantime you can add the following to your projects `composer.json`: 

```
  "conflict": {
    "symfony/symfony": ">=4.4"
  },
```

**Comment by brusch** [comment]
6.3.3 is now available!

**Comment by dpfaffenbauer** [comment]
that is actually a problem for all Pimcore 6.* releases.... So, if anyone runs Pimcore < 6.3.3, you cannot use Symfony 4.4.

**Comment by nilskm** [comment]
This still an issue? I'm a new user and I tried to update a newly installed pimcore installation and got this error. How can I downgrade symfony? I don't know how to do that. 

This is the command I ran: "COMPOSER_MEMORY_LIMIT=-1 composer update"

**Comment by nilskm** [comment]
> This still an issue? I'm a new user and I tried to update a newly installed pimcore installation and got this error. How can I downgrade symfony? I don't know how to do that.
> 
> This is the command I ran: "COMPOSER_MEMORY_LIMIT=-1 composer update"

I figured it out! I just added ""symfony/symfony": "4.3.*""  under require in composer.json. Sorry, never used composer earlier :-)
