### ISSUE TITLE
Error after document save (saveToSession)

### ISSUE THREAD

**Issue by blankse** [pimcore/pimcore#5872]
![image](https://user-images.githubusercontent.com/998558/74931925-f5cf3a80-53e0-11ea-9d23-8ac6789454f4.png)

<table>

<tbody>

<tr>

<th align="left" bgcolor="#f57900" colspan="5"><span style="background-color: #cc0000; color: #fce94f; font-size: x-large;">( ! )</span> ErrorException: Warning: Cannot bind closure to scope of internal class ReflectionProperty in var/cache/dev/ContainerF2VpKOX/SubrequestExtension_ac4dffd.php on line _133_</th>

</tr>

<tr>

<th align="left" bgcolor="#e9b96e" colspan="5">Call Stack</th>

</tr>

<tr>

<th align="center" bgcolor="#eeeeec">#</th>

<th align="left" bgcolor="#eeeeec">Time</th>

<th align="left" bgcolor="#eeeeec">Memory</th>

<th align="left" bgcolor="#eeeeec">Function</th>

<th align="left" bgcolor="#eeeeec">Location</th>

</tr>

<tr>

<td bgcolor="#eeeeec" align="center">1</td>

<td bgcolor="#eeeeec" align="center">0.0131</td>

<td bgcolor="#eeeeec" align="right">411088</td>

<td bgcolor="#eeeeec">{main}( )</td>

<td title="/var/www/blankse/pimcore-showroom/web/app.php" bgcolor="#eeeeec">.../app.php**:**0</td>

</tr>

<tr>

<td bgcolor="#eeeeec" align="center">2</td>

<td bgcolor="#eeeeec" align="center">0.4462</td>

<td bgcolor="#eeeeec" align="right">24336984</td>

<td bgcolor="#eeeeec">AppKernel->handle( ???, ???, ??? )</td>

<td title="/var/www/blankse/pimcore-showroom/web/app.php" bgcolor="#eeeeec">.../app.php**:**36</td>

</tr>

<tr>

<td bgcolor="#eeeeec" align="center">3</td>

<td bgcolor="#eeeeec" align="center">0.4481</td>

<td bgcolor="#eeeeec" align="right">24351888</td>

<td bgcolor="#eeeeec">Symfony\Component\HttpKernel\HttpKernel->handle( ???, ???, ??? )</td>

<td title="/var/www/blankse/pimcore-showroom/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php" bgcolor="#eeeeec">.../Kernel.php**:**201</td>

</tr>

<tr>

<td bgcolor="#eeeeec" align="center">4</td>

<td bgcolor="#eeeeec" align="center">0.4481</td>

<td bgcolor="#eeeeec" align="right">24352304</td>

<td bgcolor="#eeeeec">Symfony\Component\HttpKernel\HttpKernel->handleRaw( ???, ??? )</td>

<td title="/var/www/blankse/pimcore-showroom/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php" bgcolor="#eeeeec">.../HttpKernel.php**:**68</td>

</tr>

<tr>

<td bgcolor="#eeeeec" align="center">5</td>

<td bgcolor="#eeeeec" align="center">0.8825</td>

<td bgcolor="#eeeeec" align="right">39531840</td>

<td bgcolor="#eeeeec">Pimcore\Bundle\AdminBundle\Controller\Admin\Document\PageController->saveAction( ??? )</td>

<td title="/var/www/blankse/pimcore-showroom/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php" bgcolor="#eeeeec">.../HttpKernel.php**:**146</td>

</tr>

<tr>

<td bgcolor="#eeeeec" align="center">6</td>

<td bgcolor="#eeeeec" align="center">31.9925</td>

<td bgcolor="#eeeeec" align="right">83502240</td>

<td bgcolor="#eeeeec">Pimcore\Bundle\AdminBundle\Controller\Admin\Document\PageController->saveToSession( ???, ??? )</td>

<td title="/var/www/blankse/pimcore-showroom/vendor/pimcore/pimcore/bundles/AdminBundle/Controller/Admin/Document/PageController.php" bgcolor="#eeeeec">.../PageController.php**:**171</td>

</tr>

<tr>

<td bgcolor="#eeeeec" align="center">7</td>

<td bgcolor="#eeeeec" align="center">31.9926</td>

<td bgcolor="#eeeeec" align="right">83502240</td>

<td bgcolor="#eeeeec">Pimcore\Model\Element\Service::saveElementToSession( ???, ???, ??? )</td>

<td title="/var/www/blankse/pimcore-showroom/vendor/pimcore/pimcore/bundles/AdminBundle/Controller/Admin/Document/DocumentControllerBase.php" bgcolor="#eeeeec">.../DocumentControllerBase.php**:**171</td>

</tr>

<tr>

<td bgcolor="#eeeeec" align="center">8</td>

<td bgcolor="#eeeeec" align="center">31.9928</td>

<td bgcolor="#eeeeec" align="right">83504192</td>

<td bgcolor="#eeeeec">DeepCopy\DeepCopy->copy( ??? )</td>

<td title="/var/www/blankse/pimcore-showroom/vendor/pimcore/pimcore/models/Element/Service.php" bgcolor="#eeeeec">.../Service.php**:**1285</td>

</tr>

<tr>

<td bgcolor="#eeeeec" align="center">9</td>

<td bgcolor="#eeeeec" align="center">31.9928</td>

<td bgcolor="#eeeeec" align="right">83504192</td>

<td bgcolor="#eeeeec">DeepCopy\DeepCopy->recursiveCopy( ??? )</td>

<td title="/var/www/blankse/pimcore-showroom/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php" bgcolor="#eeeeec">.../DeepCopy.php**:**94</td>

</tr>

<tr>

<td bgcolor="#eeeeec" align="center">10</td>

<td bgcolor="#eeeeec" align="center">31.9931</td>

<td bgcolor="#eeeeec" align="right">83504192</td>

<td bgcolor="#eeeeec">DeepCopy\DeepCopy->copyObject( ??? )</td>

<td title="/var/www/blankse/pimcore-showroom/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php" bgcolor="#eeeeec">.../DeepCopy.php**:**144</td>

</tr>

<tr>

<td bgcolor="#eeeeec" align="center">11</td>

<td bgcolor="#eeeeec" align="center">45.1192</td>

<td bgcolor="#eeeeec" align="right">94360320</td>

<td bgcolor="#eeeeec">DeepCopy\DeepCopy->copyObjectProperty( ???, ??? )</td>

<td title="/var/www/blankse/pimcore-showroom/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php" bgcolor="#eeeeec">.../DeepCopy.php**:**208</td>

</tr>

<tr>

<td bgcolor="#eeeeec" align="center">12</td>

<td bgcolor="#eeeeec" align="center">45.1192</td>

<td bgcolor="#eeeeec" align="right">94360320</td>

<td bgcolor="#eeeeec">DeepCopy\DeepCopy->recursiveCopy( ??? )</td>

<td title="/var/www/blankse/pimcore-showroom/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php" bgcolor="#eeeeec">.../DeepCopy.php**:**252</td>

</tr>

<tr>

<td bgcolor="#eeeeec" align="center">13</td>

<td bgcolor="#eeeeec" align="center">45.1193</td>

<td bgcolor="#eeeeec" align="right">94360320</td>

<td bgcolor="#eeeeec">DeepCopy\DeepCopy->copyArray( ??? )</td>

<td title="/var/www/blankse/pimcore-showroom/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php" bgcolor="#eeeeec">.../DeepCopy.php**:**135</td>

</tr>

<tr>

<td bgcolor="#eeeeec" align="center">14</td>

<td bgcolor="#eeeeec" align="center">45.1298</td>

<td bgcolor="#eeeeec" align="right">94375224</td>

<td bgcolor="#eeeeec">DeepCopy\DeepCopy->recursiveCopy( ??? )</td>

<td title="/var/www/blankse/pimcore-showroom/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php" bgcolor="#eeeeec">.../DeepCopy.php**:**155</td>

</tr>

<tr>

<td bgcolor="#eeeeec" align="center">15</td>

<td bgcolor="#eeeeec" align="center">45.1299</td>

<td bgcolor="#eeeeec" align="right">94375224</td>

<td bgcolor="#eeeeec">DeepCopy\DeepCopy->copyObject( ??? )</td>

<td title="/var/www/blankse/pimcore-showroom/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php" bgcolor="#eeeeec">.../DeepCopy.php**:**144</td>

</tr>

<tr>

<td bgcolor="#eeeeec" align="center">16</td>

<td bgcolor="#eeeeec" align="center">45.1589</td>

<td bgcolor="#eeeeec" align="right">94412728</td>

<td bgcolor="#eeeeec">DeepCopy\DeepCopy->copyObjectProperty( ???, ??? )</td>

<td title="/var/www/blankse/pimcore-showroom/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php" bgcolor="#eeeeec">.../DeepCopy.php**:**208</td>

</tr>

<tr>

<td bgcolor="#eeeeec" align="center">17</td>

<td bgcolor="#eeeeec" align="center">45.1589</td>

<td bgcolor="#eeeeec" align="right">94412728</td>

<td bgcolor="#eeeeec">DeepCopy\DeepCopy->recursiveCopy( ??? )</td>

<td title="/var/www/blankse/pimcore-showroom/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php" bgcolor="#eeeeec">.../DeepCopy.php**:**252</td>

</tr>

<tr>

<td bgcolor="#eeeeec" align="center">18</td>

<td bgcolor="#eeeeec" align="center">45.1590</td>

<td bgcolor="#eeeeec" align="right">94412728</td>

<td bgcolor="#eeeeec">DeepCopy\DeepCopy->copyObject( ??? )</td>

<td title="/var/www/blankse/pimcore-showroom/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php" bgcolor="#eeeeec">.../DeepCopy.php**:**144</td>

</tr>

<tr>

<td bgcolor="#eeeeec" align="center">19</td>

<td bgcolor="#eeeeec" align="center">45.1590</td>

<td bgcolor="#eeeeec" align="right">94414552</td>

<td bgcolor="#eeeeec">DeepCopy\DeepCopy->copyObjectProperty( ???, ??? )</td>

<td title="/var/www/blankse/pimcore-showroom/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php" bgcolor="#eeeeec">.../DeepCopy.php**:**208</td>

</tr>

<tr>

<td bgcolor="#eeeeec" align="center">20</td>

<td bgcolor="#eeeeec" align="center">45.1591</td>

<td bgcolor="#eeeeec" align="right">94414552</td>

<td bgcolor="#eeeeec">DeepCopy\DeepCopy->recursiveCopy( ??? )</td>

<td title="/var/www/blankse/pimcore-showroom/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php" bgcolor="#eeeeec">.../DeepCopy.php**:**252</td>

</tr>

<tr>

<td bgcolor="#eeeeec" align="center">21</td>

<td bgcolor="#eeeeec" align="center">45.1591</td>

<td bgcolor="#eeeeec" align="right">94414552</td>

<td bgcolor="#eeeeec">DeepCopy\DeepCopy->copyObject( ??? )</td>

<td title="/var/www/blankse/pimcore-showroom/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php" bgcolor="#eeeeec">.../DeepCopy.php**:**144</td>

</tr>

<tr>

<td bgcolor="#eeeeec" align="center">22</td>

<td bgcolor="#eeeeec" align="center">45.1592</td>

<td bgcolor="#eeeeec" align="right">94416352</td>

<td bgcolor="#eeeeec">DeepCopy\DeepCopy->copyObjectProperty( ???, ??? )</td>

<td title="/var/www/blankse/pimcore-showroom/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php" bgcolor="#eeeeec">.../DeepCopy.php**:**208</td>

</tr>

<tr>

<td bgcolor="#eeeeec" align="center">23</td>

<td bgcolor="#eeeeec" align="center">45.1592</td>

<td bgcolor="#eeeeec" align="right">94416352</td>

<td bgcolor="#eeeeec">DeepCopy\DeepCopy->recursiveCopy( ??? )</td>

<td title="/var/www/blankse/pimcore-showroom/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php" bgcolor="#eeeeec">.../DeepCopy.php**:**252</td>

</tr>

<tr>

<td bgcolor="#eeeeec" align="center">24</td>

<td bgcolor="#eeeeec" align="center">45.1593</td>

<td bgcolor="#eeeeec" align="right">94416352</td>

<td bgcolor="#eeeeec">DeepCopy\DeepCopy->copyArray( ??? )</td>

<td title="/var/www/blankse/pimcore-showroom/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php" bgcolor="#eeeeec">.../DeepCopy.php**:**135</td>

</tr>

<tr>

<td bgcolor="#eeeeec" align="center">25</td>

<td bgcolor="#eeeeec" align="center">45.1596</td>

<td bgcolor="#eeeeec" align="right">94417048</td>

<td bgcolor="#eeeeec">DeepCopy\DeepCopy->recursiveCopy( ??? )</td>

<td title="/var/www/blankse/pimcore-showroom/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php" bgcolor="#eeeeec">.../DeepCopy.php**:**155</td>

</tr>

<tr>

<td bgcolor="#eeeeec" align="center">26</td>

<td bgcolor="#eeeeec" align="center">45.1597</td>

<td bgcolor="#eeeeec" align="right">94417048</td>

<td bgcolor="#eeeeec">DeepCopy\DeepCopy->copyObject( ??? )</td>

<td title="/var/www/blankse/pimcore-showroom/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php" bgcolor="#eeeeec">.../DeepCopy.php**:**144</td>

</tr>

<tr>

<td bgcolor="#eeeeec" align="center">27</td>

<td bgcolor="#eeeeec" align="center">45.1603</td>

<td bgcolor="#eeeeec" align="right">94422960</td>

<td bgcolor="#eeeeec">DeepCopy\DeepCopy->copyObjectProperty( ???, ??? )</td>

<td title="/var/www/blankse/pimcore-showroom/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php" bgcolor="#eeeeec">.../DeepCopy.php**:**208</td>

</tr>

<tr>

<td bgcolor="#eeeeec" align="center">28</td>

<td bgcolor="#eeeeec" align="center">45.1603</td>

<td bgcolor="#eeeeec" align="right">94422960</td>

<td bgcolor="#eeeeec">DeepCopy\DeepCopy->recursiveCopy( ??? )</td>

<td title="/var/www/blankse/pimcore-showroom/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php" bgcolor="#eeeeec">.../DeepCopy.php**:**252</td>

</tr>

<tr>

<td bgcolor="#eeeeec" align="center">29</td>

<td bgcolor="#eeeeec" align="center">45.1604</td>

<td bgcolor="#eeeeec" align="right">94422960</td>

<td bgcolor="#eeeeec">DeepCopy\DeepCopy->copyObject( ??? )</td>

<td title="/var/www/blankse/pimcore-showroom/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php" bgcolor="#eeeeec">.../DeepCopy.php**:**144</td>

</tr>

<tr>

<td bgcolor="#eeeeec" align="center">30</td>

<td bgcolor="#eeeeec" align="center">45.1607</td>

<td bgcolor="#eeeeec" align="right">94448624</td>

<td bgcolor="#eeeeec">DeepCopy\DeepCopy->copyObjectProperty( ???, ??? )</td>

<td title="/var/www/blankse/pimcore-showroom/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php" bgcolor="#eeeeec">.../DeepCopy.php**:**208</td>

</tr>

<tr>

<td bgcolor="#eeeeec" align="center">31</td>

<td bgcolor="#eeeeec" align="center">45.1607</td>

<td bgcolor="#eeeeec" align="right">94448624</td>

<td bgcolor="#eeeeec">DeepCopy\DeepCopy->recursiveCopy( ??? )</td>

<td title="/var/www/blankse/pimcore-showroom/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php" bgcolor="#eeeeec">.../DeepCopy.php**:**252</td>

</tr>

<tr>

<td bgcolor="#eeeeec" align="center">32</td>

<td bgcolor="#eeeeec" align="center">45.1608</td>

<td bgcolor="#eeeeec" align="right">94448624</td>

<td bgcolor="#eeeeec">DeepCopy\DeepCopy->copyObject( ??? )</td>

<td title="/var/www/blankse/pimcore-showroom/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php" bgcolor="#eeeeec">.../DeepCopy.php**:**144</td>

</tr>

<tr>

<td bgcolor="#eeeeec" align="center">33</td>

<td bgcolor="#eeeeec" align="center">45.1608</td>

<td bgcolor="#eeeeec" align="right">94450424</td>

<td bgcolor="#eeeeec">DeepCopy\DeepCopy->copyObjectProperty( ???, ??? )</td>

<td title="/var/www/blankse/pimcore-showroom/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php" bgcolor="#eeeeec">.../DeepCopy.php**:**208</td>

</tr>

<tr>

<td bgcolor="#eeeeec" align="center">34</td>

<td bgcolor="#eeeeec" align="center">45.1608</td>

<td bgcolor="#eeeeec" align="right">94450424</td>

<td bgcolor="#eeeeec">DeepCopy\DeepCopy->recursiveCopy( ??? )</td>

<td title="/var/www/blankse/pimcore-showroom/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php" bgcolor="#eeeeec">.../DeepCopy.php**:**252</td>

</tr>

<tr>

<td bgcolor="#eeeeec" align="center">35</td>

<td bgcolor="#eeeeec" align="center">45.1609</td>

<td bgcolor="#eeeeec" align="right">94450424</td>

<td bgcolor="#eeeeec">DeepCopy\DeepCopy->copyArray( ??? )</td>

<td title="/var/www/blankse/pimcore-showroom/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php" bgcolor="#eeeeec">.../DeepCopy.php**:**135</td>

</tr>

<tr>

<td bgcolor="#eeeeec" align="center">36</td>

<td bgcolor="#eeeeec" align="center">45.1616</td>

<td bgcolor="#eeeeec" align="right">94451120</td>

<td bgcolor="#eeeeec">DeepCopy\DeepCopy->recursiveCopy( ??? )</td>

<td title="/var/www/blankse/pimcore-showroom/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php" bgcolor="#eeeeec">.../DeepCopy.php**:**155</td>

</tr>

<tr>

<td bgcolor="#eeeeec" align="center">37</td>

<td bgcolor="#eeeeec" align="center">45.1617</td>

<td bgcolor="#eeeeec" align="right">94451120</td>

<td bgcolor="#eeeeec">DeepCopy\DeepCopy->copyObject( ??? )</td>

<td title="/var/www/blankse/pimcore-showroom/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php" bgcolor="#eeeeec">.../DeepCopy.php**:**144</td>

</tr>

<tr>

<td bgcolor="#eeeeec" align="center">38</td>

<td bgcolor="#eeeeec" align="center">45.1620</td>

<td bgcolor="#eeeeec" align="right">94455152</td>

<td bgcolor="#eeeeec">DeepCopy\DeepCopy->copyObjectProperty( ???, ??? )</td>

<td title="/var/www/blankse/pimcore-showroom/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php" bgcolor="#eeeeec">.../DeepCopy.php**:**208</td>

</tr>

<tr>

<td bgcolor="#eeeeec" align="center">39</td>

<td bgcolor="#eeeeec" align="center">45.1620</td>

<td bgcolor="#eeeeec" align="right">94455152</td>

<td bgcolor="#eeeeec">DeepCopy\DeepCopy->recursiveCopy( ??? )</td>

<td title="/var/www/blankse/pimcore-showroom/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php" bgcolor="#eeeeec">.../DeepCopy.php**:**252</td>

</tr>

<tr>

<td bgcolor="#eeeeec" align="center">40</td>

<td bgcolor="#eeeeec" align="center">45.1621</td>

<td bgcolor="#eeeeec" align="right">94455152</td>

<td bgcolor="#eeeeec">DeepCopy\DeepCopy->copyObject( ??? )</td>

<td title="/var/www/blankse/pimcore-showroom/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php" bgcolor="#eeeeec">.../DeepCopy.php**:**144</td>

</tr>

<tr>

<td bgcolor="#eeeeec" align="center">41</td>

<td bgcolor="#eeeeec" align="center">46.0997</td>

<td bgcolor="#eeeeec" align="right">95131128</td>

<td bgcolor="#eeeeec">DeepCopy\DeepCopy->copyObjectProperty( ???, ??? )</td>

<td title="/var/www/blankse/pimcore-showroom/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php" bgcolor="#eeeeec">.../DeepCopy.php**:**208</td>

</tr>

<tr>

<td bgcolor="#eeeeec" align="center">42</td>

<td bgcolor="#eeeeec" align="center">46.0997</td>

<td bgcolor="#eeeeec" align="right">95131128</td>

<td bgcolor="#eeeeec">DeepCopy\DeepCopy->recursiveCopy( ??? )</td>

<td title="/var/www/blankse/pimcore-showroom/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php" bgcolor="#eeeeec">.../DeepCopy.php**:**252</td>

</tr>

<tr>

<td bgcolor="#eeeeec" align="center">43</td>

<td bgcolor="#eeeeec" align="center">46.0998</td>

<td bgcolor="#eeeeec" align="right">95131128</td>

<td bgcolor="#eeeeec">DeepCopy\DeepCopy->copyArray( ??? )</td>

<td title="/var/www/blankse/pimcore-showroom/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php" bgcolor="#eeeeec">.../DeepCopy.php**:**135</td>

</tr>

<tr>

<td bgcolor="#eeeeec" align="center">44</td>

<td bgcolor="#eeeeec" align="center">46.0998</td>

<td bgcolor="#eeeeec" align="right">95131128</td>

<td bgcolor="#eeeeec">DeepCopy\DeepCopy->recursiveCopy( ??? )</td>

<td title="/var/www/blankse/pimcore-showroom/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php" bgcolor="#eeeeec">.../DeepCopy.php**:**155</td>

</tr>

<tr>

<td bgcolor="#eeeeec" align="center">45</td>

<td bgcolor="#eeeeec" align="center">46.0999</td>

<td bgcolor="#eeeeec" align="right">95131128</td>

<td bgcolor="#eeeeec">DeepCopy\DeepCopy->copyArray( ??? )</td>

<td title="/var/www/blankse/pimcore-showroom/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php" bgcolor="#eeeeec">.../DeepCopy.php**:**135</td>

</tr>

<tr>

<td bgcolor="#eeeeec" align="center">46</td>

<td bgcolor="#eeeeec" align="center">46.1000</td>

<td bgcolor="#eeeeec" align="right">95131128</td>

<td bgcolor="#eeeeec">DeepCopy\DeepCopy->recursiveCopy( ??? )</td>

<td title="/var/www/blankse/pimcore-showroom/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php" bgcolor="#eeeeec">.../DeepCopy.php**:**155</td>

</tr>

<tr>

<td bgcolor="#eeeeec" align="center">47</td>

<td bgcolor="#eeeeec" align="center">46.1000</td>

<td bgcolor="#eeeeec" align="right">95131128</td>

<td bgcolor="#eeeeec">DeepCopy\DeepCopy->copyObject( ??? )</td>

<td title="/var/www/blankse/pimcore-showroom/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php" bgcolor="#eeeeec">.../DeepCopy.php**:**144</td>

</tr>

<tr>

<td bgcolor="#eeeeec" align="center">48</td>

<td bgcolor="#eeeeec" align="center">46.1001</td>

<td bgcolor="#eeeeec" align="right">95132928</td>

<td bgcolor="#eeeeec">DeepCopy\DeepCopy->copyObjectProperty( ???, ??? )</td>

<td title="/var/www/blankse/pimcore-showroom/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php" bgcolor="#eeeeec">.../DeepCopy.php**:**208</td>

</tr>

<tr>

<td bgcolor="#eeeeec" align="center">49</td>

<td bgcolor="#eeeeec" align="center">46.1001</td>

<td bgcolor="#eeeeec" align="right">95132928</td>

<td bgcolor="#eeeeec">DeepCopy\DeepCopy->recursiveCopy( ??? )</td>

<td title="/var/www/blankse/pimcore-showroom/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php" bgcolor="#eeeeec">.../DeepCopy.php**:**252</td>

</tr>

<tr>

<td bgcolor="#eeeeec" align="center">50</td>

<td bgcolor="#eeeeec" align="center">46.1002</td>

<td bgcolor="#eeeeec" align="right">95132928</td>

<td bgcolor="#eeeeec">DeepCopy\DeepCopy->copyObject( ??? )</td>

<td title="/var/www/blankse/pimcore-showroom/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php" bgcolor="#eeeeec">.../DeepCopy.php**:**144</td>

</tr>

<tr>

<td bgcolor="#eeeeec" align="center">51</td>

<td bgcolor="#eeeeec" align="center">46.1006</td>

<td bgcolor="#eeeeec" align="right">95137984</td>

<td bgcolor="#eeeeec">DeepCopy\DeepCopy->copyObjectProperty( ???, ??? )</td>

<td title="/var/www/blankse/pimcore-showroom/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php" bgcolor="#eeeeec">.../DeepCopy.php**:**208</td>

</tr>

<tr>

<td bgcolor="#eeeeec" align="center">52</td>

<td bgcolor="#eeeeec" align="center">46.1006</td>

<td bgcolor="#eeeeec" align="right">95137984</td>

<td bgcolor="#eeeeec">DeepCopy\DeepCopy->recursiveCopy( ??? )</td>

<td title="/var/www/blankse/pimcore-showroom/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php" bgcolor="#eeeeec">.../DeepCopy.php**:**252</td>

</tr>

<tr>

<td bgcolor="#eeeeec" align="center">53</td>

<td bgcolor="#eeeeec" align="center">46.1007</td>

<td bgcolor="#eeeeec" align="right">95137984</td>

<td bgcolor="#eeeeec">DeepCopy\DeepCopy->copyObject( ??? )</td>

<td title="/var/www/blankse/pimcore-showroom/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php" bgcolor="#eeeeec">.../DeepCopy.php**:**144</td>

</tr>

<tr>

<td bgcolor="#eeeeec" align="center">54</td>

<td bgcolor="#eeeeec" align="center">46.1009</td>

<td bgcolor="#eeeeec" align="right">95141056</td>

<td bgcolor="#eeeeec">DeepCopy\DeepCopy->copyObjectProperty( ???, ??? )</td>

<td title="/var/www/blankse/pimcore-showroom/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php" bgcolor="#eeeeec">.../DeepCopy.php**:**208</td>

</tr>

<tr>

<td bgcolor="#eeeeec" align="center">55</td>

<td bgcolor="#eeeeec" align="center">46.1009</td>

<td bgcolor="#eeeeec" align="right">95141056</td>

<td bgcolor="#eeeeec">DeepCopy\DeepCopy->recursiveCopy( ??? )</td>

<td title="/var/www/blankse/pimcore-showroom/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php" bgcolor="#eeeeec">.../DeepCopy.php**:**252</td>

</tr>

<tr>

<td bgcolor="#eeeeec" align="center">56</td>

<td bgcolor="#eeeeec" align="center">46.1010</td>

<td bgcolor="#eeeeec" align="right">95141056</td>

<td bgcolor="#eeeeec">DeepCopy\DeepCopy->copyObject( ??? )</td>

<td title="/var/www/blankse/pimcore-showroom/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php" bgcolor="#eeeeec">.../DeepCopy.php**:**144</td>

</tr>

<tr>

<td bgcolor="#eeeeec" align="center">57</td>

<td bgcolor="#eeeeec" align="center">46.1011</td>

<td bgcolor="#eeeeec" align="right">95144800</td>

<td bgcolor="#eeeeec">DeepCopy\DeepCopy->copyObjectProperty( ???, ??? )</td>

<td title="/var/www/blankse/pimcore-showroom/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php" bgcolor="#eeeeec">.../DeepCopy.php**:**208</td>

</tr>

<tr>

<td bgcolor="#eeeeec" align="center">58</td>

<td bgcolor="#eeeeec" align="center">46.1011</td>

<td bgcolor="#eeeeec" align="right">95144800</td>

<td bgcolor="#eeeeec">DeepCopy\DeepCopy->recursiveCopy( ??? )</td>

<td title="/var/www/blankse/pimcore-showroom/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php" bgcolor="#eeeeec">.../DeepCopy.php**:**252</td>

</tr>

<tr>

<td bgcolor="#eeeeec" align="center">59</td>

<td bgcolor="#eeeeec" align="center">46.1012</td>

<td bgcolor="#eeeeec" align="right">95144800</td>

<td bgcolor="#eeeeec">DeepCopy\DeepCopy->copyObject( ??? )</td>

<td title="/var/www/blankse/pimcore-showroom/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php" bgcolor="#eeeeec">.../DeepCopy.php**:**144</td>

</tr>

<tr>

<td bgcolor="#eeeeec" align="center">60</td>

<td bgcolor="#eeeeec" align="center">52.8259</td>

<td bgcolor="#eeeeec" align="right">104336888</td>

<td bgcolor="#eeeeec">DeepCopy\DeepCopy->copyObjectProperty( ???, ??? )</td>

<td title="/var/www/blankse/pimcore-showroom/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php" bgcolor="#eeeeec">.../DeepCopy.php**:**208</td>

</tr>

<tr>

<td bgcolor="#eeeeec" align="center">61</td>

<td bgcolor="#eeeeec" align="center">52.8260</td>

<td bgcolor="#eeeeec" align="right">104336888</td>

<td bgcolor="#eeeeec">DeepCopy\DeepCopy->recursiveCopy( ??? )</td>

<td title="/var/www/blankse/pimcore-showroom/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php" bgcolor="#eeeeec">.../DeepCopy.php**:**252</td>

</tr>

<tr>

<td bgcolor="#eeeeec" align="center">62</td>

<td bgcolor="#eeeeec" align="center">52.8261</td>

<td bgcolor="#eeeeec" align="right">104336888</td>

<td bgcolor="#eeeeec">DeepCopy\DeepCopy->copyObject( ??? )</td>

<td title="/var/www/blankse/pimcore-showroom/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php" bgcolor="#eeeeec">.../DeepCopy.php**:**144</td>

</tr>

<tr>

<td bgcolor="#eeeeec" align="center">63</td>

<td bgcolor="#eeeeec" align="center">52.8261</td>

<td bgcolor="#eeeeec" align="right">104339960</td>

<td bgcolor="#eeeeec">DeepCopy\DeepCopy->copyObjectProperty( ???, ??? )</td>

<td title="/var/www/blankse/pimcore-showroom/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php" bgcolor="#eeeeec">.../DeepCopy.php**:**208</td>

</tr>

<tr>

<td bgcolor="#eeeeec" align="center">64</td>

<td bgcolor="#eeeeec" align="center">52.8262</td>

<td bgcolor="#eeeeec" align="right">104339960</td>

<td bgcolor="#eeeeec">DeepCopy\DeepCopy->recursiveCopy( ??? )</td>

<td title="/var/www/blankse/pimcore-showroom/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php" bgcolor="#eeeeec">.../DeepCopy.php**:**252</td>

</tr>

<tr>

<td bgcolor="#eeeeec" align="center">65</td>

<td bgcolor="#eeeeec" align="center">52.8263</td>

<td bgcolor="#eeeeec" align="right">104339960</td>

<td bgcolor="#eeeeec">DeepCopy\DeepCopy->copyArray( ??? )</td>

<td title="/var/www/blankse/pimcore-showroom/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php" bgcolor="#eeeeec">.../DeepCopy.php**:**135</td>

</tr>

<tr>

<td bgcolor="#eeeeec" align="center">66</td>

<td bgcolor="#eeeeec" align="center">52.8269</td>

<td bgcolor="#eeeeec" align="right">104344336</td>

<td bgcolor="#eeeeec">DeepCopy\DeepCopy->recursiveCopy( ??? )</td>

<td title="/var/www/blankse/pimcore-showroom/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php" bgcolor="#eeeeec">.../DeepCopy.php**:**155</td>

</tr>

<tr>

<td bgcolor="#eeeeec" align="center">67</td>

<td bgcolor="#eeeeec" align="center">52.8271</td>

<td bgcolor="#eeeeec" align="right">104344336</td>

<td bgcolor="#eeeeec">DeepCopy\DeepCopy->copyArray( ??? )</td>

<td title="/var/www/blankse/pimcore-showroom/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php" bgcolor="#eeeeec">.../DeepCopy.php**:**135</td>

</tr>

<tr>

<td bgcolor="#eeeeec" align="center">68</td>

<td bgcolor="#eeeeec" align="center">53.5159</td>

<td bgcolor="#eeeeec" align="right">105155704</td>

<td bgcolor="#eeeeec">DeepCopy\DeepCopy->recursiveCopy( ??? )</td>

<td title="/var/www/blankse/pimcore-showroom/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php" bgcolor="#eeeeec">.../DeepCopy.php**:**155</td>

</tr>

<tr>

<td bgcolor="#eeeeec" align="center">69</td>

<td bgcolor="#eeeeec" align="center">53.5160</td>

<td bgcolor="#eeeeec" align="right">105155704</td>

<td bgcolor="#eeeeec">DeepCopy\DeepCopy->copyArray( ??? )</td>

<td title="/var/www/blankse/pimcore-showroom/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php" bgcolor="#eeeeec">.../DeepCopy.php**:**135</td>

</tr>

<tr>

<td bgcolor="#eeeeec" align="center">70</td>

<td bgcolor="#eeeeec" align="center">53.5160</td>

<td bgcolor="#eeeeec" align="right">105155704</td>

<td bgcolor="#eeeeec">DeepCopy\DeepCopy->recursiveCopy( ??? )</td>

<td title="/var/www/blankse/pimcore-showroom/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php" bgcolor="#eeeeec">.../DeepCopy.php**:**155</td>

</tr>

<tr>

<td bgcolor="#eeeeec" align="center">71</td>

<td bgcolor="#eeeeec" align="center">53.5161</td>

<td bgcolor="#eeeeec" align="right">105155704</td>

<td bgcolor="#eeeeec">DeepCopy\DeepCopy->copyArray( ??? )</td>

<td title="/var/www/blankse/pimcore-showroom/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php" bgcolor="#eeeeec">.../DeepCopy.php**:**135</td>

</tr>

<tr>

<td bgcolor="#eeeeec" align="center">72</td>

<td bgcolor="#eeeeec" align="center">53.5161</td>

<td bgcolor="#eeeeec" align="right">105155704</td>

<td bgcolor="#eeeeec">DeepCopy\DeepCopy->recursiveCopy( ??? )</td>

<td title="/var/www/blankse/pimcore-showroom/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php" bgcolor="#eeeeec">.../DeepCopy.php**:**155</td>

</tr>

<tr>

<td bgcolor="#eeeeec" align="center">73</td>

<td bgcolor="#eeeeec" align="center">53.5162</td>

<td bgcolor="#eeeeec" align="right">105155704</td>

<td bgcolor="#eeeeec">DeepCopy\DeepCopy->copyObject( ??? )</td>

<td title="/var/www/blankse/pimcore-showroom/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php" bgcolor="#eeeeec">.../DeepCopy.php**:**144</td>

</tr>

<tr>

<td bgcolor="#eeeeec" align="center">74</td>

<td bgcolor="#eeeeec" align="center">53.5163</td>

<td bgcolor="#eeeeec" align="right">105158776</td>

<td bgcolor="#eeeeec">DeepCopy\DeepCopy->copyObjectProperty( ???, ??? )</td>

<td title="/var/www/blankse/pimcore-showroom/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php" bgcolor="#eeeeec">.../DeepCopy.php**:**208</td>

</tr>

<tr>

<td bgcolor="#eeeeec" align="center">75</td>

<td bgcolor="#eeeeec" align="center">53.5163</td>

<td bgcolor="#eeeeec" align="right">105158776</td>

<td bgcolor="#eeeeec">DeepCopy\DeepCopy->recursiveCopy( ??? )</td>

<td title="/var/www/blankse/pimcore-showroom/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php" bgcolor="#eeeeec">.../DeepCopy.php**:**252</td>

</tr>

<tr>

<td bgcolor="#eeeeec" align="center">76</td>

<td bgcolor="#eeeeec" align="center">53.5164</td>

<td bgcolor="#eeeeec" align="right">105158776</td>

<td bgcolor="#eeeeec">DeepCopy\DeepCopy->copyObject( ??? )</td>

<td title="/var/www/blankse/pimcore-showroom/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php" bgcolor="#eeeeec">.../DeepCopy.php**:**144</td>

</tr>

<tr>

<td bgcolor="#eeeeec" align="center">77</td>

<td bgcolor="#eeeeec" align="center">53.5169</td>

<td bgcolor="#eeeeec" align="right">105162272</td>

<td bgcolor="#eeeeec">DeepCopy\DeepCopy->copyObjectProperty( ???, ??? )</td>

<td title="/var/www/blankse/pimcore-showroom/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php" bgcolor="#eeeeec">.../DeepCopy.php**:**208</td>

</tr>

<tr>

<td bgcolor="#eeeeec" align="center">78</td>

<td bgcolor="#eeeeec" align="center">53.5169</td>

<td bgcolor="#eeeeec" align="right">105162272</td>

<td bgcolor="#eeeeec">DeepCopy\DeepCopy->recursiveCopy( ??? )</td>

<td title="/var/www/blankse/pimcore-showroom/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php" bgcolor="#eeeeec">.../DeepCopy.php**:**252</td>

</tr>

<tr>

<td bgcolor="#eeeeec" align="center">79</td>

<td bgcolor="#eeeeec" align="center">53.5170</td>

<td bgcolor="#eeeeec" align="right">105162272</td>

<td bgcolor="#eeeeec">DeepCopy\DeepCopy->copyObject( ??? )</td>

<td title="/var/www/blankse/pimcore-showroom/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php" bgcolor="#eeeeec">.../DeepCopy.php**:**144</td>

</tr>

<tr>

<td bgcolor="#eeeeec" align="center">80</td>

<td bgcolor="#eeeeec" align="center">53.5171</td>

<td bgcolor="#eeeeec" align="right">105164704</td>

<td bgcolor="#eeeeec">DeepCopy\DeepCopy->copyObjectProperty( ???, ??? )</td>

<td title="/var/www/blankse/pimcore-showroom/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php" bgcolor="#eeeeec">.../DeepCopy.php**:**208</td>

</tr>

<tr>

<td bgcolor="#eeeeec" align="center">81</td>

<td bgcolor="#eeeeec" align="center">53.5171</td>

<td bgcolor="#eeeeec" align="right">105164704</td>

<td bgcolor="#eeeeec">DeepCopy\DeepCopy->recursiveCopy( ??? )</td>

<td title="/var/www/blankse/pimcore-showroom/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php" bgcolor="#eeeeec">.../DeepCopy.php**:**252</td>

</tr>

<tr>

<td bgcolor="#eeeeec" align="center">82</td>

<td bgcolor="#eeeeec" align="center">53.5172</td>

<td bgcolor="#eeeeec" align="right">105164704</td>

<td bgcolor="#eeeeec">DeepCopy\DeepCopy->copyArray( ??? )</td>

<td title="/var/www/blankse/pimcore-showroom/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php" bgcolor="#eeeeec">.../DeepCopy.php**:**135</td>

</tr>

<tr>

<td bgcolor="#eeeeec" align="center">83</td>

<td bgcolor="#eeeeec" align="center">53.6200</td>

<td bgcolor="#eeeeec" align="right">105244912</td>

<td bgcolor="#eeeeec">DeepCopy\DeepCopy->recursiveCopy( ??? )</td>

<td title="/var/www/blankse/pimcore-showroom/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php" bgcolor="#eeeeec">.../DeepCopy.php**:**155</td>

</tr>

<tr>

<td bgcolor="#eeeeec" align="center">84</td>

<td bgcolor="#eeeeec" align="center">53.6201</td>

<td bgcolor="#eeeeec" align="right">105244912</td>

<td bgcolor="#eeeeec">DeepCopy\DeepCopy->copyObject( ??? )</td>

<td title="/var/www/blankse/pimcore-showroom/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php" bgcolor="#eeeeec">.../DeepCopy.php**:**144</td>

</tr>

<tr>

<td bgcolor="#eeeeec" align="center">85</td>

<td bgcolor="#eeeeec" align="center">53.6202</td>

<td bgcolor="#eeeeec" align="right">105247968</td>

<td bgcolor="#eeeeec">DeepCopy\DeepCopy->copyObjectProperty( ???, ??? )</td>

<td title="/var/www/blankse/pimcore-showroom/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php" bgcolor="#eeeeec">.../DeepCopy.php**:**208</td>

</tr>

<tr>

<td bgcolor="#eeeeec" align="center">86</td>

<td bgcolor="#eeeeec" align="center">53.6202</td>

<td bgcolor="#eeeeec" align="right">105247968</td>

<td bgcolor="#eeeeec">DeepCopy\DeepCopy->recursiveCopy( ??? )</td>

<td title="/var/www/blankse/pimcore-showroom/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php" bgcolor="#eeeeec">.../DeepCopy.php**:**252</td>

</tr>

<tr>

<td bgcolor="#eeeeec" align="center">87</td>

<td bgcolor="#eeeeec" align="center">53.6203</td>

<td bgcolor="#eeeeec" align="right">105247968</td>

<td bgcolor="#eeeeec">DeepCopy\DeepCopy->copyObject( ??? )</td>

<td title="/var/www/blankse/pimcore-showroom/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php" bgcolor="#eeeeec">.../DeepCopy.php**:**144</td>

</tr>

<tr>

<td bgcolor="#eeeeec" align="center">88</td>

<td bgcolor="#eeeeec" align="center">53.6722</td>

<td bgcolor="#eeeeec" align="right">105317440</td>

<td bgcolor="#eeeeec">DeepCopy\DeepCopy->copyObjectProperty( ???, ??? )</td>

<td title="/var/www/blankse/pimcore-showroom/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php" bgcolor="#eeeeec">.../DeepCopy.php**:**208</td>

</tr>

<tr>

<td bgcolor="#eeeeec" align="center">89</td>

<td bgcolor="#eeeeec" align="center">53.6722</td>

<td bgcolor="#eeeeec" align="right">105317440</td>

<td bgcolor="#eeeeec">DeepCopy\DeepCopy->recursiveCopy( ??? )</td>

<td title="/var/www/blankse/pimcore-showroom/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php" bgcolor="#eeeeec">.../DeepCopy.php**:**252</td>

</tr>

<tr>

<td bgcolor="#eeeeec" align="center">90</td>

<td bgcolor="#eeeeec" align="center">53.6723</td>

<td bgcolor="#eeeeec" align="right">105317440</td>

<td bgcolor="#eeeeec">DeepCopy\DeepCopy->copyArray( ??? )</td>

<td title="/var/www/blankse/pimcore-showroom/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php" bgcolor="#eeeeec">.../DeepCopy.php**:**135</td>

</tr>

<tr>

<td bgcolor="#eeeeec" align="center">91</td>

<td bgcolor="#eeeeec" align="center">53.6723</td>

<td bgcolor="#eeeeec" align="right">105317440</td>

<td bgcolor="#eeeeec">DeepCopy\DeepCopy->recursiveCopy( ??? )</td>

<td title="/var/www/blankse/pimcore-showroom/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php" bgcolor="#eeeeec">.../DeepCopy.php**:**155</td>

</tr>

<tr>

<td bgcolor="#eeeeec" align="center">92</td>

<td bgcolor="#eeeeec" align="center">53.6724</td>

<td bgcolor="#eeeeec" align="right">105317440</td>

<td bgcolor="#eeeeec">DeepCopy\DeepCopy->copyObject( ??? )</td>

<td title="/var/www/blankse/pimcore-showroom/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php" bgcolor="#eeeeec">.../DeepCopy.php**:**144</td>

</tr>

<tr>

<td bgcolor="#eeeeec" align="center">93</td>

<td bgcolor="#eeeeec" align="center">53.6727</td>

<td bgcolor="#eeeeec" align="right">105324880</td>

<td bgcolor="#eeeeec">DeepCopy\DeepCopy->copyObjectProperty( ???, ??? )</td>

<td title="/var/www/blankse/pimcore-showroom/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php" bgcolor="#eeeeec">.../DeepCopy.php**:**208</td>

</tr>

<tr>

<td bgcolor="#eeeeec" align="center">94</td>

<td bgcolor="#eeeeec" align="center">53.6728</td>

<td bgcolor="#eeeeec" align="right">105324880</td>

<td bgcolor="#eeeeec">DeepCopy\DeepCopy->recursiveCopy( ??? )</td>

<td title="/var/www/blankse/pimcore-showroom/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php" bgcolor="#eeeeec">.../DeepCopy.php**:**252</td>

</tr>

<tr>

<td bgcolor="#eeeeec" align="center">95</td>

<td bgcolor="#eeeeec" align="center">53.6729</td>

<td bgcolor="#eeeeec" align="right">105324880</td>

<td bgcolor="#eeeeec">DeepCopy\DeepCopy->copyArray( ??? )</td>

<td title="/var/www/blankse/pimcore-showroom/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php" bgcolor="#eeeeec">.../DeepCopy.php**:**135</td>

</tr>

<tr>

<td bgcolor="#eeeeec" align="center">96</td>

<td bgcolor="#eeeeec" align="center">53.6729</td>

<td bgcolor="#eeeeec" align="right">105324880</td>

<td bgcolor="#eeeeec">DeepCopy\DeepCopy->recursiveCopy( ??? )</td>

<td title="/var/www/blankse/pimcore-showroom/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php" bgcolor="#eeeeec">.../DeepCopy.php**:**155</td>

</tr>

<tr>

<td bgcolor="#eeeeec" align="center">97</td>

<td bgcolor="#eeeeec" align="center">53.6730</td>

<td bgcolor="#eeeeec" align="right">105324880</td>

<td bgcolor="#eeeeec">DeepCopy\DeepCopy->copyObject( ??? )</td>

<td title="/var/www/blankse/pimcore-showroom/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php" bgcolor="#eeeeec">.../DeepCopy.php**:**144</td>

</tr>

<tr>

<td bgcolor="#eeeeec" align="center">98</td>

<td bgcolor="#eeeeec" align="center">53.6732</td>

<td bgcolor="#eeeeec" align="right">105332320</td>

<td bgcolor="#eeeeec">DeepCopy\DeepCopy->copyObjectProperty( ???, ??? )</td>

<td title="/var/www/blankse/pimcore-showroom/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php" bgcolor="#eeeeec">.../DeepCopy.php**:**208</td>

</tr>

<tr>

<td bgcolor="#eeeeec" align="center">99</td>

<td bgcolor="#eeeeec" align="center">53.6732</td>

<td bgcolor="#eeeeec" align="right">105332320</td>

<td bgcolor="#eeeeec">DeepCopy\DeepCopy->recursiveCopy( ??? )</td>

<td title="/var/www/blankse/pimcore-showroom/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php" bgcolor="#eeeeec">.../DeepCopy.php**:**252</td>

</tr>

<tr>

<td bgcolor="#eeeeec" align="center">100</td>

<td bgcolor="#eeeeec" align="center">53.6733</td>

<td bgcolor="#eeeeec" align="right">105332320</td>

<td bgcolor="#eeeeec">DeepCopy\DeepCopy->copyArray( ??? )</td>

<td title="/var/www/blankse/pimcore-showroom/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php" bgcolor="#eeeeec">.../DeepCopy.php**:**135</td>

</tr>

<tr>

<td bgcolor="#eeeeec" align="center">101</td>

<td bgcolor="#eeeeec" align="center">53.6733</td>

<td bgcolor="#eeeeec" align="right">105332320</td>

<td bgcolor="#eeeeec">DeepCopy\DeepCopy->recursiveCopy( ??? )</td>

<td title="/var/www/blankse/pimcore-showroom/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php" bgcolor="#eeeeec">.../DeepCopy.php**:**155</td>

</tr>

<tr>

<td bgcolor="#eeeeec" align="center">102</td>

<td bgcolor="#eeeeec" align="center">53.6734</td>

<td bgcolor="#eeeeec" align="right">105332320</td>

<td bgcolor="#eeeeec">DeepCopy\DeepCopy->copyObject( ??? )</td>

<td title="/var/www/blankse/pimcore-showroom/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php" bgcolor="#eeeeec">.../DeepCopy.php**:**144</td>

</tr>

<tr>

<td bgcolor="#eeeeec" align="center">103</td>

<td bgcolor="#eeeeec" align="center">53.6737</td>

<td bgcolor="#eeeeec" align="right">105339760</td>

<td bgcolor="#eeeeec">DeepCopy\DeepCopy->copyObjectProperty( ???, ??? )</td>

<td title="/var/www/blankse/pimcore-showroom/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php" bgcolor="#eeeeec">.../DeepCopy.php**:**208</td>

</tr>

<tr>

<td bgcolor="#eeeeec" align="center">104</td>

<td bgcolor="#eeeeec" align="center">53.6738</td>

<td bgcolor="#eeeeec" align="right">105339760</td>

<td bgcolor="#eeeeec">DeepCopy\DeepCopy->recursiveCopy( ??? )</td>

<td title="/var/www/blankse/pimcore-showroom/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php" bgcolor="#eeeeec">.../DeepCopy.php**:**252</td>

</tr>

<tr>

<td bgcolor="#eeeeec" align="center">105</td>

<td bgcolor="#eeeeec" align="center">53.6739</td>

<td bgcolor="#eeeeec" align="right">105339760</td>

<td bgcolor="#eeeeec">DeepCopy\DeepCopy->copyArray( ??? )</td>

<td title="/var/www/blankse/pimcore-showroom/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php" bgcolor="#eeeeec">.../DeepCopy.php**:**135</td>

</tr>

<tr>

<td bgcolor="#eeeeec" align="center">106</td>

<td bgcolor="#eeeeec" align="center">53.6739</td>

<td bgcolor="#eeeeec" align="right">105339760</td>

<td bgcolor="#eeeeec">DeepCopy\DeepCopy->recursiveCopy( ??? )</td>

<td title="/var/www/blankse/pimcore-showroom/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php" bgcolor="#eeeeec">.../DeepCopy.php**:**155</td>

</tr>

<tr>

<td bgcolor="#eeeeec" align="center">107</td>

<td bgcolor="#eeeeec" align="center">53.6740</td>

<td bgcolor="#eeeeec" align="right">105339760</td>

<td bgcolor="#eeeeec">DeepCopy\DeepCopy->copyObject( ??? )</td>

<td title="/var/www/blankse/pimcore-showroom/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php" bgcolor="#eeeeec">.../DeepCopy.php**:**144</td>

</tr>

<tr>

<td bgcolor="#eeeeec" align="center">108</td>

<td bgcolor="#eeeeec" align="center">53.6745</td>

<td bgcolor="#eeeeec" align="right">105347200</td>

<td bgcolor="#eeeeec">DeepCopy\DeepCopy->copyObjectProperty( ???, ??? )</td>

<td title="/var/www/blankse/pimcore-showroom/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php" bgcolor="#eeeeec">.../DeepCopy.php**:**208</td>

</tr>

<tr>

<td bgcolor="#eeeeec" align="center">109</td>

<td bgcolor="#eeeeec" align="center">53.6745</td>

<td bgcolor="#eeeeec" align="right">105347200</td>

<td bgcolor="#eeeeec">DeepCopy\DeepCopy->recursiveCopy( ??? )</td>

<td title="/var/www/blankse/pimcore-showroom/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php" bgcolor="#eeeeec">.../DeepCopy.php**:**252</td>

</tr>

<tr>

<td bgcolor="#eeeeec" align="center">110</td>

<td bgcolor="#eeeeec" align="center">53.6746</td>

<td bgcolor="#eeeeec" align="right">105347200</td>

<td bgcolor="#eeeeec">DeepCopy\DeepCopy->copyArray( ??? )</td>

<td title="/var/www/blankse/pimcore-showroom/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php" bgcolor="#eeeeec">.../DeepCopy.php**:**135</td>

</tr>

<tr>

<td bgcolor="#eeeeec" align="center">111</td>

<td bgcolor="#eeeeec" align="center">53.6746</td>

<td bgcolor="#eeeeec" align="right">105347200</td>

<td bgcolor="#eeeeec">DeepCopy\DeepCopy->recursiveCopy( ??? )</td>

<td title="/var/www/blankse/pimcore-showroom/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php" bgcolor="#eeeeec">.../DeepCopy.php**:**155</td>

</tr>

<tr>

<td bgcolor="#eeeeec" align="center">112</td>

<td bgcolor="#eeeeec" align="center">53.6747</td>

<td bgcolor="#eeeeec" align="right">105347200</td>

<td bgcolor="#eeeeec">DeepCopy\DeepCopy->copyArray( ??? )</td>

<td title="/var/www/blankse/pimcore-showroom/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php" bgcolor="#eeeeec">.../DeepCopy.php**:**135</td>

</tr>

<tr>

<td bgcolor="#eeeeec" align="center">113</td>

<td bgcolor="#eeeeec" align="center">53.6747</td>

<td bgcolor="#eeeeec" align="right">105347200</td>

<td bgcolor="#eeeeec">DeepCopy\DeepCopy->recursiveCopy( ??? )</td>

<td title="/var/www/blankse/pimcore-showroom/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php" bgcolor="#eeeeec">.../DeepCopy.php**:**155</td>

</tr>

<tr>

<td bgcolor="#eeeeec" align="center">114</td>

<td bgcolor="#eeeeec" align="center">53.6748</td>

<td bgcolor="#eeeeec" align="right">105347200</td>

<td bgcolor="#eeeeec">DeepCopy\DeepCopy->copyObject( ??? )</td>

<td title="/var/www/blankse/pimcore-showroom/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php" bgcolor="#eeeeec">.../DeepCopy.php**:**144</td>

</tr>

<tr>

<td bgcolor="#eeeeec" align="center">115</td>

<td bgcolor="#eeeeec" align="center">53.6925</td>

<td bgcolor="#eeeeec" align="right">105376056</td>

<td bgcolor="#eeeeec">DeepCopy\DeepCopy->copyObjectProperty( ???, ??? )</td>

<td title="/var/www/blankse/pimcore-showroom/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php" bgcolor="#eeeeec">.../DeepCopy.php**:**208</td>

</tr>

<tr>

<td bgcolor="#eeeeec" align="center">116</td>

<td bgcolor="#eeeeec" align="center">53.6925</td>

<td bgcolor="#eeeeec" align="right">105376056</td>

<td bgcolor="#eeeeec">DeepCopy\DeepCopy->recursiveCopy( ??? )</td>

<td title="/var/www/blankse/pimcore-showroom/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php" bgcolor="#eeeeec">.../DeepCopy.php**:**252</td>

</tr>

<tr>

<td bgcolor="#eeeeec" align="center">117</td>

<td bgcolor="#eeeeec" align="center">53.6926</td>

<td bgcolor="#eeeeec" align="right">105376056</td>

<td bgcolor="#eeeeec">DeepCopy\DeepCopy->copyArray( ??? )</td>

<td title="/var/www/blankse/pimcore-showroom/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php" bgcolor="#eeeeec">.../DeepCopy.php**:**135</td>

</tr>

<tr>

<td bgcolor="#eeeeec" align="center">118</td>

<td bgcolor="#eeeeec" align="center">56.1892</td>

<td bgcolor="#eeeeec" align="right">108570224</td>

<td bgcolor="#eeeeec">DeepCopy\DeepCopy->recursiveCopy( ??? )</td>

<td title="/var/www/blankse/pimcore-showroom/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php" bgcolor="#eeeeec">.../DeepCopy.php**:**155</td>

</tr>

<tr>

<td bgcolor="#eeeeec" align="center">119</td>

<td bgcolor="#eeeeec" align="center">56.1893</td>

<td bgcolor="#eeeeec" align="right">108570224</td>

<td bgcolor="#eeeeec">DeepCopy\DeepCopy->copyObject( ??? )</td>

<td title="/var/www/blankse/pimcore-showroom/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php" bgcolor="#eeeeec">.../DeepCopy.php**:**144</td>

</tr>

<tr>

<td bgcolor="#eeeeec" align="center">120</td>

<td bgcolor="#eeeeec" align="center">56.1895</td>

<td bgcolor="#eeeeec" align="right">108574720</td>

<td bgcolor="#eeeeec">DeepCopy\DeepCopy->copyObjectProperty( ???, ??? )</td>

<td title="/var/www/blankse/pimcore-showroom/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php" bgcolor="#eeeeec">.../DeepCopy.php**:**208</td>

</tr>

<tr>

<td bgcolor="#eeeeec" align="center">121</td>

<td bgcolor="#eeeeec" align="center">56.1895</td>

<td bgcolor="#eeeeec" align="right">108574720</td>

<td bgcolor="#eeeeec">[getValue](http://www.php.net/ReflectionProperty.getValue) ( ??? )</td>

<td title="/var/www/blankse/pimcore-showroom/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php" bgcolor="#eeeeec">.../DeepCopy.php**:**249</td>

</tr>

<tr>

<td bgcolor="#eeeeec" align="center">122</td>

<td bgcolor="#eeeeec" align="center">56.1895</td>

<td bgcolor="#eeeeec" align="right">108574760</td>

<td bgcolor="#eeeeec">SubrequestExtension_ac4dffd->__get( ??? )</td>

<td title="/var/www/blankse/pimcore-showroom/vendor/myclabs/deep-copy/src/DeepCopy/DeepCopy.php" bgcolor="#eeeeec">.../DeepCopy.php**:**249</td>

</tr>

<tr>

<td bgcolor="#eeeeec" align="center">123</td>

<td bgcolor="#eeeeec" align="center">56.1897</td>

<td bgcolor="#eeeeec" align="right">108674808</td>

<td bgcolor="#eeeeec">[bindTo](http://www.php.net/Closure.bindTo) ( ???, ??? )</td>

<td title="/var/www/blankse/pimcore-showroom/var/cache/dev/ContainerF2VpKOX/SubrequestExtension_ac4dffd.php" bgcolor="#eeeeec">.../SubrequestExtension_ac4dffd.php**:**133</td>

</tr>

<tr>

<td bgcolor="#eeeeec" align="center">124</td>

<td bgcolor="#eeeeec" align="center">56.1897</td>

<td bgcolor="#eeeeec" align="right">108675888</td>

<td bgcolor="#eeeeec">Symfony\Component\Debug\ErrorHandler->handleError( ???, ???, ???, ???, ??? )</td>

<td title="/var/www/blankse/pimcore-showroom/var/cache/dev/ContainerF2VpKOX/SubrequestExtension_ac4dffd.php" bgcolor="#eeeeec">.../SubrequestExtension_ac4dffd.php**:**133</td>

</tr>

</tbody>

</table>

**Comment by dvesh3** [comment]
fixed or related? https://github.com/pimcore/pimcore/issues/5866

**Comment by blankse** [comment]
I am on the current master. 

Without #5866 I get following error:
![image](https://user-images.githubusercontent.com/998558/74932276-b35a2d80-53e1-11ea-95ff-0056e59d9a2d.png)

Maybe related, but not fixed

**Comment by brusch** [comment]
I'm wondering why saveToSession is called, when a document gets saved,  ... imho that shouldn't be necessary.

**Comment by blankse** [comment]
After debugging I think it's the Areablock Element which makes a problem. 
This have a request property -> this have the controller -> this have the container...

**Comment by dvesh3** [comment]
@blankse yes, but container issue is already fixed in https://github.com/pimcore/pimcore/commit/02efc01a8c8ab0badd7b3e792a2b3904076b7bcb

@brusch Agree! I can't either think of a scenario :/

**Comment by dvesh3** [comment]
@blankse cannot reproduce your issue, not even on demo.pimcore.fun. Can you please share more insights?

**Comment by dpfaffenbauer** [comment]
It maybe has something todo with nested bricks? @blankse how does your document look like

**Comment by blankse** [comment]
Yes I have an areablock:
`{{ pimcore_areablock('content', areaBlockConfig).render() }}`

Than I have an brick with blocks, which have also areablocks (columns, tabs, collapse):
```
        {% for i in pimcore_iterate_block(pimcore_block('contentblock')) %}
            ...
                    {{ pimcore_areablock('content', areaBlockConfig).render() }}
            ...
        {% endfor %}
```

**Comment by blankse** [comment]
BTW: I have `PIMCORE_PHP_ERROR_REPORTING`' set to `E_ALL`

**Comment by blankse** [comment]
@dvesh3 It is not the container. It is the InlineFragmentRenderer dependency of an Controller Helper class, which run to the problem:

DeepCopy->copyObject()
$newObject types
- \Pimcore\Model\Document\Page
- \Pimcore\Model\Document\Tag\Areablock
- \Pimcore\Templating\Model\ViewModel
- \Symfony\Component\HttpFoundation\ParameterBag
- \Pimcore\Model\Document\Tag\Area\Info
- \Symfony\Component\HttpFoundation\Request
- \Symfony\Component\HttpFoundation\ParameterBag
- \AppBundle\Controller\DefaultController
- \AppBundle\Helper\BannerHelper
- \Symfony\Component\HttpKernel\Fragment\InlineFragmentRenderer
- \Symfony\Component\HttpKernel\HttpKernel
- \Symfony\Component\HttpKernel\Debug\TraceableEventDispatcher
- \Symfony\Component\EventDispatcher\EventDispatcher
- \Pimcore\Bundle\CoreBundle\EventListener\LegacyTemplateListener
- \Pimcore\Bundle\CoreBundle\Templating\LegacyTemplateGuesser
- \Symfony\Bundle\FrameworkBundle\Templating\DelegatingEngine
- \Symfony\Bundle\TwigBundle\TwigEngine
- \Twig\Environment
- \__TwigTemplate_e30be6bee75d8e27af198720096ff8883efe38b53cb39fbdf71ef33504047235
- ...
-

**Comment by dvesh3** [comment]
@blankse `\AppBundle\Helper\BannerHelper` looks suspicious. can you please try to disable it?

**Comment by blankse** [comment]
@dvesh3 Why should I do this? I need this dependency to render a template for my top banner.

Why work this in the previous versions and now not anymore?

I also don't understand why all of this has to be cloned? Isn't the document with its tags enough without all the dependencies? See my created PR.

**Comment by dvesh3** [comment]
@blankse I'm not saying you should stop using it. Just trying to dig out the root cause, wihch answers your query("Why work this in the previous versions and now not anymore?") as it is not reproducible at my end.

I saw your PR but maybe this is not required at all if we kick saveToSession on document save.

@brusch any suggestions?

**Comment by dpfaffenbauer** [comment]
But if you kick it, it still will have issues for previews wouldn't it?

**Comment by dvesh3** [comment]
@dpfaffenbauer good point! it will have issues since it calls the same method. 

also edit version
![image](https://user-images.githubusercontent.com/5137917/74956699-ca5f4680-5406-11ea-857a-2854f6fe455b.png)

**Comment by dvesh3** [comment]
@blankse @dpfaffenbauer the root cause is this line https://github.com/pimcore/pimcore/blob/aecbc447f35487709bc32221fb0a5014279e6b1a/models/Document/PageSnippet.php#L663
which before save renders the document in editmode to get all element tags to find missing values for required editables so it loads the view of all elements. Also preview and edit version has no effect.

I have pushed changes in commit https://github.com/pimcore/pimcore/commit/cc7908c45bebb2f69937f9788309e584661cf3bf to use a safe copy of document for checking missing required values and would like to keep the changes requested by blankse as it will not harm.

**Comment by BenjaminEden** [comment]
Related to #5843 ?

**Comment by dvesh3** [comment]
@BenjaminEden it seems so as i see "Container.. is not cloneable" exception in your stacktrace. could please confirm if this PR fixes your issue? https://github.com/pimcore/pimcore/pull/5875

**Comment by BenjaminEden** [comment]
@dvesh3 I've tried #5866 and 02efc01 and it fixed my issue!

**Comment by brusch** [comment]
@dvesh3 regarding the need of calling `saveToSession()` on publish: 

In my opinion in would be sufficient to call `Service::removeElementFromSession()` here, since the latest content is then anyway stored in the published document: 
https://github.com/pimcore/pimcore/blob/9b0a4ebdc831dbd5cc21d314388ee34b8d4f8703/bundles/AdminBundle/Controller/Admin/Document/PageController.php#L171

But we can leave it as it is for now, as it doesn't hurt and the session is anyway cleaned up as soon as the document gets closed.
