### ISSUE TITLE
[Bug] Error loading editables using Turkish language

### ISSUE THREAD

**Issue by ramundomario** [pimcore/pimcore#8295]
# Bug Report

### Expected behavior

Load editables within documents with Turkish language (PHP layout)

### Actual behavior

![Screenshot from 2021-02-26 15-05-41](https://user-images.githubusercontent.com/16133208/109312114-f21d9180-7846-11eb-9925-5341fedd4e2d.png)
![Screenshot from 2021-02-26 15-04-47](https://user-images.githubusercontent.com/16133208/109312117-f34ebe80-7846-11eb-9a4c-93b23f4cf525.png)

### Steps to reproduce 

- Add Turkish language in System settings
- Change language in [footer](http://demo.pimcore.fun/admin/login/deeplink?document_170_page) from German to English
- This error is thrown:
![Screenshot from 2021-02-26 15-11-43](https://user-images.githubusercontent.com/16133208/109312461-5fc9bd80-7847-11eb-92f4-7d38cf0be82f.png)

Seems same error discussed in #4476

**Comment by brusch** [comment]
Same issue, since we're using Composer autoloader, there, nothing we can do about it. Sorry.

**Comment by francescomulas** [comment]
hi Brush, same issue on pimcore demo
![image](https://user-images.githubusercontent.com/55782677/109492578-7a8c7400-7a8b-11eb-9f92-b6a4377815d5.png)

**Comment by fashxp** [comment]
> hi Brush, same issue on pimcore demo
> ![image](https://user-images.githubusercontent.com/55782677/109492578-7a8c7400-7a8b-11eb-9f92-b6a4377815d5.png)

up again

**Comment by francescomulas** [comment]
Hi Christian,
 issue still appear with turkish language.

Sorry but, as you can see, it's down again:
https://demo.pimcore.fun/

**Comment by brusch** [comment]
Probably because someone changes the locale ...

**Comment by francescomulas** [comment]
Turkish language seems to be unsupported from pimcore at the moment, right?

**Comment by GALCF** [comment]
UPDATE: It does not seem to fix it on my staging machine, sorry.

@brusch  
Might this be a possible hotfix to the turkish locale include-problems?  
The bug seems to get activated by [this listener line](https://github.com/pimcore/pimcore/blob/10.x/bundles/CoreBundle/EventListener/Frontend/LocaleListener.php#L74) so I overwrote the `setlocale` call only, and only for "tr".

```php
<?php

namespace AppBundle\EventSubscriber;

use Locale;
use Symfony\Component\EventDispatcher\EventSubscriberInterface;
use Symfony\Component\HttpKernel\Event\RequestEvent;
use Symfony\Component\HttpKernel\KernelEvents;

class TurkishLocaleFixSubscriber implements EventSubscriberInterface
{
    /**
     * @return mixed[]
     */
    public static function getSubscribedEvents()
    {
        return [
            KernelEvents::REQUEST => ['onKernelRequest', 2],
        ];
    }

    /**
     * @var string|null
     */
    private $lastLocale = null;

    public function onKernelRequest(RequestEvent $event): void
    {
        $locale = $event->getRequest()->getLocale();

        if ($locale && $locale !== $this->lastLocale) {
            $this->lastLocale = $locale;

            $primaryLanguage = Locale::getPrimaryLanguage($locale);

            if ($primaryLanguage === 'tr') {
                setlocale(LC_ALL, 'C');
            }
        }
    }
}
```

**Comment by GALCF** [comment]
@brusch  
Second try, this seems to work for me:

The [PrefixLoader](https://github.com/pimcore/pimcore/blob/10.x/lib/Model/Document/Editable/Loader/PrefixLoader.php#L32) uses locale-aware php functions.

This implementation does not change the i for example:

```php
<?php

declare(strict_types = 1);

/**
 * Pimcore
 *
 * This source file is available under two different licenses:
 * - GNU General Public License version 3 (GPLv3)
 * - Pimcore Commercial License (PCL)
 * Full copyright and license information is available in
 * LICENSE.md which is distributed with this source code.
 *
 *  @copyright  Copyright (c) Pimcore GmbH (http://www.pimcore.org)
 *  @license    http://www.pimcore.org/license     GPLv3 and PCL
 */

namespace Pimcore\Model\Document\Editable\Loader;

use Pimcore\Loader\ImplementationLoader\PrefixLoader as BasePrefixLoader;

/**
 * @internal
 */
final class PrefixLoader extends BasePrefixLoader
{
    /**
     * {@inheritdoc}
     */
    protected function normalizeName(string $name): string
    {
        // old implementation, locale-aware
        // return ucfirst(strtolower($name));

        $firstChar  = mb_strtoupper(mb_substr($name, 0, 1));
        $otherChars = mb_strtolower(mb_substr($name, 1));

        return $firstChar . $otherChars;
    }
}
```

**Comment by ramundomario** [comment]
@brusch This seems to be a Pimcore bug since Pimcore uses locale-aware php functions (as mentioned by @GALCF ) and not a Composer bug

**Comment by brusch** [comment]
@ramundomario fixed by #9630

**Comment by GALCF** [comment]
@brusch I found some more instances where the use of locale-aware php functions throw errors in turkish locale settings

`lcfirst` seems to be a problem, too:
- Create a DataObject with an attribute
- The attribute name has to have an i in it (e.g. 'isDefault' checkbox data type)
-  A call to `getByIsDefault(/* [...] */)` in turkish locale context throws an error `Class: DataObject\Concrete => call to undefined static method getByIsDefault`
- This is because the i gets interpreted differently in the turkish locale [right here](https://github.com/pimcore/pimcore/blob/v10.2.9/models/DataObject/Concrete.php#L603)

Other instances might also cause currently unknown issues:  
- https://github.com/pimcore/pimcore/search?q=lcfirst
- https://github.com/pimcore/pimcore/search?q=ucfirst

**Comment by GALCF** [comment]
According to [this RFC](https://wiki.php.net/rfc/strtolower-ascii) the following functions are affected:

> The following PHP string functions will do ASCII case conversion:
> - strtolower
> - strtoupper
> - stristr
> - stripos
> - strripos
> - lcfirst
> - ucfirst
> - ucwords
> - str_ireplace

**Comment by brusch** [comment]
@GALCF could you please implement the same approach for the remaining affected places (in a PR)? I think it would make sense to put the logic into a shared function 😊

**Comment by rberneder** [comment]
@GALCF @brusch Is there any update to this issue?
Wouldn't it be meaningful to reopen this issue, since it is not solved yet?

**Comment by brusch** [comment]
@rberneder this issue was about editables, which is solved 😉For the other things we're waiting for PRs.
